### ISSUE TITLE
编译脚本乱写啊

### ISSUE THREAD

**Issue by widon1104** [q77190858/dde-sys-monitor-plugin#1]
cd -p ~/plugin-guide/sys_monitor/build/

别人怎么可能有 ~/plugin-guide/sys_monitor啊，别人在自己电脑上一运行这个脚本，目录就被清空了，很危险的

基本最后一句dde-dock也不需要，dde-dock会自动重启的 

还有最要不要在编译脚本里面写rm -rf *这样的语句，很危险的，创建一个空目录cd进去就可以了啊

**Comment by q77190858** [comment]
恩恩，已修复
