### ISSUE TITLE
字体出现剃头剃尾

### ISSUE THREAD

**Issue by Jiandanlangman** [q77190858/dde-sys-monitor-plugin#12]
时尚模式下是正常的
高校模式一开始显示正常，当我打开任意一个没固定在任务栏的App时，插件的字体出现了剃尾现象
看起来好像整个文字突然往下移动了好多像素，无论怎么调整高度，大小，间距，问题始终存在
用的是你最新编译的版本
4K屏+2倍缩放

**Comment by q77190858** [comment]
这个是dde-dock存在的问题，要么拉高dock要么调低插件高度
