### ISSUE TITLE
字体似乎还是没有对齐

### ISSUE THREAD

**Issue by jay763190097** [q77190858/dde-sys-monitor-plugin#4]
![深度截图_选择区域_20190620230508](https://user-images.githubusercontent.com/16317178/59859723-deeacb00-93af-11e9-87a4-6a6ec3567597.png)
可以再加一个CPU和显卡温度

**Comment by jay763190097** [comment]
用的最新版编译的

**Comment by q77190858** [comment]
现在看看已经对齐了，温度我再研究一下
