### ISSUE TITLE
有没有考虑一下做成动画形式啊

### ISSUE THREAD

**Issue by widon1104** [q77190858/dde-sys-monitor-plugin#5]
不知道作者用没用过gnome的插件system monitor
https://extensions.gnome.org/extension/120/system-monitor/
这款插件以动画的形式显示CPU，网速，硬盘，内存的情况，而且可以自己配置哪一项或者多项显示在面板上 ，所以这款插件的各项数值可以改成动画形式显示吗，改成动画形式有很多好处
1）动画形式不容易让用户分心，如果面板上面老是有数字在动，会导致用户分心
2）动画显示更直观
3）动画会显示历史数值
下面是system monitor监控CPU的截图
![system monitor(1)](https://user-images.githubusercontent.com/12093211/60003047-76943600-969c-11e9-89b1-1f0cb1467f8b.png)

**Comment by q77190858** [comment]
我在xubuntu上用过类似的，正在考虑加上这种动态曲线图效果

**Comment by q77190858** [comment]
已经参考了indicator-multiload加入了图表模式，了却了一桩心愿
