### ISSUE TITLE
The plugin libsys_monitor.so is not compatible with the system

### ISSUE THREAD

**Issue by iatneh** [q77190858/dde-sys-monitor-plugin#9]
从README.md中下载编译好的文件安装，重启dde-dock后提示如下

![image](https://user-images.githubusercontent.com/2985793/79818017-5961ee00-83b9-11ea-918f-9ae134246bbb.png)
![image](https://user-images.githubusercontent.com/2985793/79818078-7eeef780-83b9-11ea-9e69-0f330fdcfb2b.png)

**Comment by q77190858** [comment]
it seems to be Qt version's problem. also can you complie plugin yourself so that compatible problem can be solved as the readme.md's guide.
